apiVersion: v1
kind: Service
metadata:
  name: image-frontend-service
spec:
  type: NodePort
  selector:
    app: image-frontend
  ports:
    - port: 80
      targetPort: 80      
      nodePort: 30086
