apiVersion: v1
kind: Service
metadata:
  name: joomla-db
  labels:
    app: joomla-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: joomla-db
  clusterIP: None