apiVersion: v1
kind: Service
metadata:
  name: joomla-service
  labels:
    app: joomla
spec:
  type: NodePort
  selector:
    app: joomla
  ports:
    - port: 80       
      targetPort: 80      
      nodePort: 30080
      name: http
